/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajesh
 */
public class display extends javax.swing.JFrame {

    /**
     * Creates new form display
     */
    public display() {
        initComponents();
        show_user();
    }
    public ArrayList<User> userlist(){
        ArrayList<User> userlist = new ArrayList<>();
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/exam","root","root");
            String query1 = "select * from details";
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            User user;
            while (rs.next()){
                user = new User(rs.getcname("cname"),rs.getproduct("product"),rs.getquantity("quantity"),rs.getcontact("contact"),rs.getemail("email"),rs.getno("no"));
                userslist.add(user);
            }
        }
        catch(SQLException | HeadlessException ex)
            {
            JOptionPane.showMessageDialog(null,ex);
            }
        
        return userlist;

    }
    public void show_user(){
        ArrayList<User> list = userlist();
        DefaultTableModel model=(DefaultTableModel)display.getModel();
        Object[] row = new Object[6];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getcname();
            row[1]=list.get(i).getproduct();
            row[2]=list.get(i).getquantity();
            row[3]=list.get(i).getcontact();
            row[4]=list.get(i).getemail();
            row[5]=list.get(i).getno();
            model.addRow(row);
        }
        
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        examPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("examPU").createEntityManager();
        detailsQuery = java.beans.Beans.isDesignTime() ? null : examPUEntityManager.createQuery("SELECT d FROM details d");
        detailsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : detailsQuery.getResultList();
        detailsQuery1 = java.beans.Beans.isDesignTime() ? null : examPUEntityManager.createQuery("SELECT d FROM details d");
        detailsList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : detailsQuery1.getResultList();
        detailsQuery2 = java.beans.Beans.isDesignTime() ? null : examPUEntityManager.createQuery("SELECT d FROM details d");
        detailsList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : detailsQuery2.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cname", "product", "quantity", "contact", "email", "no"
            }
        ));
        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<exam.details> detailsList;
    private java.util.List<exam.details> detailsList1;
    private java.util.List<exam.details> detailsList2;
    private javax.persistence.Query detailsQuery;
    private javax.persistence.Query detailsQuery1;
    private javax.persistence.Query detailsQuery2;
    private javax.swing.JTable display;
    private javax.persistence.EntityManager examPUEntityManager;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
